from enum import Enum


class ProfessionKey(Enum):
    WRITER = 'WRITER'
    OPERATOR = 'OPERATOR'
    EDITOR = 'EDITOR'
    COMPOSER = 'COMPOSER'
    PRODUCER_USSR = 'PRODUCER_USSR'
    TRANSLATOR = 'TRANSLATOR'
    DIRECTOR = 'DIRECTOR'
    DESIGN = 'DESIGN'
    PRODUCER = 'PRODUCER'
    ACTOR = 'ACTOR'
    VOICE_DIRECTOR = 'VOICE_DIRECTOR'
    HIMSELF = 'HIMSELF'
    HRONO_TITR_MALE = 'HRONO_TITR_MALE'
    UNKNOWN = 'UNKNOWN'
